[project]
name = "mcp-campusx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.14.2",
    "supabase>=2.8.1",
    "python-dotenv>=1.0.0",
    "dotenv>=0.9.9",
    "psycopg2-binary>=2.9.9",
]
